#!/usr/bin/env ruby

# hookit is installed as a bundled app, so we need bundler to load it for us
$:.unshift  '/opt/gonano/hookit/vendor/bundle'
require 'bundler/setup'

# load hookit/setup to bootstrap hookit and import the dsl
require 'hookit/setup'

# IMPORTANT NOTE: docker container must be run with --priviledged="true"

# set up persistance
file "/etc/nanoinit.d/eth00" do
  content <<-EOF
    ifconfig eth0:0 #{payload[:ips][:default]}
  EOF
  mode 0755
end

# bring up interface
execute "bring up vip" do
  command <<-EOF
    ifconfig eth0:0 #{payload[:ips][:default]}
  EOF
end
