#!/usr/bin/env ruby

# hookit is installed as a bundled app, so we need bundler to load it for us
$:.unshift  '/opt/gonano/hookit/vendor/bundle'
require 'bundler/setup'

# load hookit/setup to bootstrap hookit and import the dsl
require 'hookit/setup'
require 'json'

include Hooky::Mongodb

config = converge( CONFIG_DEFAULTS, payload[:config] || {} )

plan = {
  redundant: false,
  horizontal: false,
  users: [],
  ips: [:default],
  port: 27017,
  behaviors: [:migratable, :backupable]
}

puts JSON.pretty_generate(plan)