#!/usr/bin/env ruby

# hookit is installed as a bundled app, so we need bundler to load it for us
$:.unshift  '/opt/gonano/hookit/vendor/bundle'
require 'bundler/setup'

# load hookit/setup to bootstrap hookit and import the dsl
require 'hookit/setup'

include Hooky::Mongodb

config = converge( CONFIG_DEFAULTS, payload[:config] )

directory '/data/etc/flip'

# set flip.conf
template '/data/etc/flip/flip.conf' do
  mode 0644
  variables ({
    payload: payload
  })
end

if ["default", "primary", "secondary"].include? payload[:member][:role]
  # set mongodb.conf
  template "/data/etc/mongodb/mongod.conf" do
    source 'mongodb-repl.conf.erb'
    mode 0644
    variables ({ config: config })
    owner 'gonano'
    group 'gonano'
  end

elsif "arbitrator" == payload[:member][:role]
  # set mongodb config
  directory '/data/var/db/mongodb' do
    owner 'gonano'
    group 'gonano'
  end

  directory '/var/log/mongodb' do
    owner 'gonano'
    group 'gonano'
  end

  directory '/data/var/run' do
    owner 'gonano'
    group 'gonano'
  end

  # create log file
  file '/data/var/log/mongodb/mongodb.log' do
    owner 'gonano'
    group 'gonano'
  end

  # set mongodb config
  directory '/data/etc/mongodb' do
    owner 'gonano'
    group 'gonano'
  end

  template "/data/etc/mongodb/mongod.conf" do
    source 'mongodb-repl.conf.erb'
    mode 0644
    variables ({ config: config })
    owner 'gonano'
    group 'gonano'
  end

end
