#!/usr/bin/env ruby

# hookit is installed as a bundled app, so we need bundler to load it for us
$:.unshift  '/opt/gonano/hookit/vendor/bundle'
require 'bundler/setup'

# load hookit/setup to bootstrap hookit and import the dsl
require 'hookit/setup'

service 'db' do
  action :disable
  init :runit
  only_if {`sv status db` =~ /^run/}
  not_if { !Dir.exist?('/etc/service/db') }
end

service 'flip' do
  action :disable
  init :runit
  only_if {`sv status flip` =~ /^run/}
  not_if { !Dir.exist?('/etc/service/flip') }
end

directory '/etc/service/db' do
  action :delete
  not_if { !Dir.exist?('/etc/service/db') }
end

directory '/etc/service/flip' do
  action :delete
  not_if { !Dir.exist?('/etc/service/flip') }
end
