#!/usr/bin/env ruby

# hookit is installed as a bundled app, so we need bundler to load it for us
$:.unshift  '/opt/gonano/hookit/vendor/bundle'
require 'bundler/setup'

# load hookit/setup to bootstrap hookit and import the dsl
require 'hookit/setup'

payload[:members].each do |member|

  if ['default', 'primary', 'secondary'].include? member[:role]

    execute "send diff data to new member" do
      command "rsync --delete -a /data/var/db/mongodb/. #{member[:local_ip]}:/data/var/db/mongodb/"
    end

  end
end
