#!/usr/bin/env ruby

# hookit is installed as a bundled app, so we need bundler to load it for us
$:.unshift  '/opt/gonano/hookit/vendor/bundle'
require 'bundler/setup'

# load hookit/setup to bootstrap hookit and import the dsl
require 'hookit/setup'

include Hooky::Mongodb

# Setup
converged_config = converge( Hooky::Mongodb::CONFIG_DEFAULTS, payload[:config] || {} )

local_md5 = execute "local md5" do
  command "cat /var/nanobox/hooks.md5"
  not_if { ! ::File.exists? "/var/nanobox/hooks.md5" }
end

aws_md5 = execute "aws md5" do
  command "curl -f -k https://d1ormdui8qdvue.cloudfront.net/hooks/mongodb-#{converged_config[:hook_ref]}.md5"
end

if local_md5 != aws_md5
  execute "update hooks" do
    command <<-END
bash -c 'curl \
    -f \
    -k \
    https://d1ormdui8qdvue.cloudfront.net/hooks/mongodb-#{converged_config[:hook_ref]}.tgz \
      | tar -xz -C /opt/nanobox/hooks && \
  curl \
    -f \
    -k \
    -o /var/nanobox/hooks.md5 \
    https://d1ormdui8qdvue.cloudfront.net/hooks/mongodb-#{converged_config[:hook_ref]}.md5'
END
  end
end
